### ISSUE TITLE
Separate unit and integration tests

### ISSUE THREAD

**Issue by luke-grassroot** [grassrootza/grassroot-platform#26]
Use JUnit @Category annotation and surefire/failsafe plugins to separate out unit tests and integration tests, so the former run quickly and the latter can be made much more extensive (true "automated" testing).

**Comment by luke-grassroot** [comment]
Almost done. Can run with "mvn verify", and just specify by either adding "IT" to end of Class name or @Category annotation. Next will be to separate unit & integration tests and build out full coverage on each. Will open separate issues for both.

Last minor thing on this is that the integration tests load spring boot then shut it down, and on shut down that causes a bunch of errors on the JMS listener, which get in the way of seeing test results. We should fix if not a headache to do so. Posting logs of shutdown errrors below.

**Comment by luke-grassroot** [comment]
2015-11-17 11:01:55.905  INFO 9360 --- [MQ ShutdownHook] o.apache.activemq.broker.BrokerService   : Apache ActiveMQ 5.10.2 (localhost, ID:luke-Surface-Pro-3-51087-1447750911176-0:1) is shutting down
2015-11-17 11:01:55.905  INFO 9360 --- [       Thread-3] ationConfigEmbeddedWebApplicationContext : Closing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@2483eb07: startup date [Tue Nov 17 11:01:41 SAST 2015]; root of context hierarchy
2015-11-17 11:01:55.922  INFO 9360 --- [       Thread-3] o.s.c.support.DefaultLifecycleProcessor  : Stopping beans in phase 2147483647
2015-11-17 11:01:55.936  INFO 9360 --- [m://localhost#0] o.s.j.l.SimpleMessageListenerContainer   : Trying to recover from JMS Connection exception: javax.jms.JMSException: peer (vm://localhost#1) stopped.
2015-11-17 11:01:55.938  WARN 9360 --- [m://localhost#0] o.a.activemq.jms.pool.PooledSession      : Caught exception trying close() when putting session back into the pool, will invalidate. javax.jms.JMSException: Peer (vm://localhost#1) disposed.

javax.jms.JMSException: Peer (vm://localhost#1) disposed.
	at org.apache.activemq.util.JMSExceptionSupport.create(JMSExceptionSupport.java:72)
	at org.apache.activemq.ActiveMQConnection.doAsyncSendPacket(ActiveMQConnection.java:1332)
	at org.apache.activemq.ActiveMQConnection.asyncSendPacket(ActiveMQConnection.java:1324)
	at org.apache.activemq.ActiveMQSession.asyncSendPacket(ActiveMQSession.java:2007)
	at org.apache.activemq.ActiveMQMessageConsumer.doClose(ActiveMQMessageConsumer.java:723)
	at org.apache.activemq.ActiveMQMessageConsumer.close(ActiveMQMessageConsumer.java:708)
	at org.apache.activemq.jms.pool.PooledSession.close(PooledSession.java:108)
	at org.apache.activemq.jms.pool.PooledConnection.cleanupAllLoanedSessions(PooledConnection.java:257)
	at org.apache.activemq.jms.pool.PooledConnection.close(PooledConnection.java:85)
	at org.springframework.jms.connection.ConnectionFactoryUtils.releaseConnection(ConnectionFactoryUtils.java:80)
	at org.springframework.jms.listener.AbstractJmsListeningContainer.refreshSharedConnection(AbstractJmsListeningContainer.java:395)
	at org.springframework.jms.listener.SimpleMessageListenerContainer.onException(SimpleMessageListenerContainer.java:242)
	at org.apache.activemq.ActiveMQConnection$5.run(ActiveMQConnection.java:2005)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.activemq.transport.TransportDisposedIOException: Peer (vm://localhost#1) disposed.
	at org.apache.activemq.transport.vm.VMTransport.oneway(VMTransport.java:92)
	at org.apache.activemq.transport.MutexTransport.oneway(MutexTransport.java:68)
	at org.apache.activemq.transport.ResponseCorrelator.oneway(ResponseCorrelator.java:60)
	at org.apache.activemq.ActiveMQConnection.doAsyncSendPacket(ActiveMQConnection.java:1330)
	... 14 common frames omitted

2015-11-17 11:01:55.946 ERROR 9360 --- [pool-2-thread-1] o.a.activemq.ActiveMQMessageConsumer     : ID:luke-Surface-Pro-3-51087-1447750911176-3:1:6:1 failed to delivered acknowledgements

javax.jms.JMSException: Peer (vm://localhost#1) disposed.
	at org.apache.activemq.util.JMSExceptionSupport.create(JMSExceptionSupport.java:72)
	at org.apache.activemq.ActiveMQConnection.doAsyncSendPacket(ActiveMQConnection.java:1332)
	at org.apache.activemq.ActiveMQConnection.asyncSendPacket(ActiveMQConnection.java:1324)
	at org.apache.activemq.ActiveMQSession.asyncSendPacket(ActiveMQSession.java:2007)
	at org.apache.activemq.ActiveMQSession.sendAck(ActiveMQSession.java:2173)
	at org.apache.activemq.ActiveMQMessageConsumer$4.run(ActiveMQMessageConsumer.java:789)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.activemq.transport.TransportDisposedIOException: Peer (vm://localhost#1) disposed.
	at org.apache.activemq.transport.vm.VMTransport.oneway(VMTransport.java:92)
	at org.apache.activemq.transport.MutexTransport.oneway(MutexTransport.java:68)
	at org.apache.activemq.transport.ResponseCorrelator.oneway(ResponseCorrelator.java:60)
	at org.apache.activemq.ActiveMQConnection.doAsyncSendPacket(ActiveMQConnection.java:1330)
	... 9 common frames omitted

2015-11-17 11:01:55.958 ERROR 9360 --- [m://localhost#0] o.s.j.l.SimpleMessageListenerContainer   : Encountered non-recoverable JMSException

javax.jms.JMSException: peer (vm://localhost#1) stopped.
	at org.apache.activemq.util.JMSExceptionSupport.create(JMSExceptionSupport.java:54)
	at org.apache.activemq.ActiveMQConnection.onAsyncException(ActiveMQConnection.java:1998)
	at org.apache.activemq.ActiveMQConnection.onException(ActiveMQConnection.java:2017)
	at org.apache.activemq.transport.TransportFilter.onException(TransportFilter.java:101)
	at org.apache.activemq.transport.ResponseCorrelator.onException(ResponseCorrelator.java:126)
	at org.apache.activemq.transport.TransportFilter.onException(TransportFilter.java:101)
	at org.apache.activemq.transport.vm.VMTransport.stop(VMTransport.java:207)
	at org.apache.activemq.transport.TransportFilter.stop(TransportFilter.java:65)
	at org.apache.activemq.transport.TransportFilter.stop(TransportFilter.java:65)
	at org.apache.activemq.transport.ResponseCorrelator.stop(ResponseCorrelator.java:132)
	at org.apache.activemq.broker.TransportConnection.doStop(TransportConnection.java:1147)
	at org.apache.activemq.broker.TransportConnection$4.run(TransportConnection.java:1113)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.activemq.transport.TransportDisposedIOException: peer (vm://localhost#1) stopped.
	... 9 common frames omitted

2015-11-17 11:01:55.991  INFO 9360 --- [MQ ShutdownHook] o.a.activemq.broker.TransportConnector   : Connector vm://localhost stopped

**Comment by luke-grassroot** [comment]
Closed in web app. Some tests in services are slow on 'test', and might be considered integration, but until that becomes a more serious issue, am closing this. The other testing issues remain open.
