### ISSUE TITLE
Adding roles to groups throwing Psql error

### ISSUE THREAD

**Issue by luke-grassroot** [grassrootza/grassroot-platform#37]
Tests pass, but then same calls fail on local pg, indicating an H2/psql discrepancy. Logs:

2015-11-19 18:40:33.692  INFO 4417 --- [http-nio-8443-exec-4] z.o.g.s.GroupAccessControlManager        : ZOG: Adding permissions for this group ... Group{groupName='Testing group', id=1, createdDateTime=2015-10-30 19:03:10.187, createdByUser=User{firstName='Luke', lastName='Jordan', phoneNumber='27813074085', displayName='Luke Jordan', languageCode='en', id=1, createdDateTime=2015-10-30 19:00:26.174, username='27813074085', enabled=true, version=5}, reminderMinutes=0, version=13, parent=null}
2015-11-19 18:40:33.693  INFO 4417 --- [http-nio-8443-exec-4] z.o.g.s.GroupAccessControlManager        : ZOG: Adding them to this user ... User{firstName='null', lastName='null', phoneNumber='27833756275', displayName='Emma Jordan', languageCode='null', id=3, createdDateTime=2015-11-02 22:16:01.74, username='27833756275', enabled=true, version=2}
2015-11-19 18:40:33.693  INFO 4417 --- [http-nio-8443-exec-4] z.o.g.s.GroupAccessControlManager        : ZOG: Adding this set of permissions ... [GROUP_PERMISSION_FORCE_ADD_MEMBER, GROUP_PERMISSION_AUTHORIZE_SUBGROUP, GROUP_PERMISSION_DELETE_GROUP_MEMBER, GROUP_PERMISSION_DELINK_SUBGROUP, GROUP_PERMISSION_ADD_GROUP_MEMBER, GROUP_PERMISSION_UPDATE_GROUP_DETAILS]

​[6:41] 
right before it threw the same error again. so the permission set is not null either

​[6:42] 
here's the rest of the stack again:

​[6:42] 
GROUP_PERMISSION_ADD_GROUP_MEMBER, GROUP_PERMISSION_UPDATE_GROUP_DETAILS]
2015-11-19 18:40:33.708  INFO 4417 --- [http-nio-8443-exec-4] o.s.b.f.xml.XmlBeanDefinitionReader      : Loading XML bean definitions from class path resource [org/springframework/jdbc/support/sql-error-codes.xml]
2015-11-19 18:40:33.783  INFO 4417 --- [http-nio-8443-exec-4] o.s.jdbc.support.SQLErrorCodesFactory    : SQLErrorCodes loaded: [DB2, Derby, H2, HSQL, Informix, MS-SQL, MySQL, Oracle, PostgreSQL, Sybase, Hana]
2015-11-19 18:40:33.818 ERROR 4417 --- [http-nio-8443-exec-4] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.RuntimeException: Could not add group permissions for user] with root cause

org.postgresql.util.PSQLException: ERROR: syntax error at or near "call"
 Position: 1
    at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2270)
    at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1998)
    at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:255)
    at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:570)
    at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:406)
    at org.postgresql.jdbc2.AbstractJdbc2Statement.executeQuery(AbstractJdbc2Statement.java:286)
    at org.springframework.jdbc.core.JdbcTemplate$1QueryStatementCallback.doInStatement(JdbcTemplate.java:455)
    at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:405)
    at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:471)
    at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:481)
    at org.springframework.jdbc.core.JdbcTemplate.queryForObject(JdbcTemplate.java:491)
    at org.springframework.jdbc.core.JdbcTemplate.queryForObject(JdbcTemplate.java:497)
    at org.springframework.jdbc.core.JdbcTemplate.queryForLong(JdbcTemplate.java:503)
    at org.springframework.security.acls.jdbc.JdbcMutableAclService.createOrRetrieveSidPrimaryKey(JdbcMutableAclService.java:222)
    at org.springframework.security.acls.jdbc.JdbcMutableAclService.createObjectIdentity(JdbcMutableAclService.java:155)
    at org.springframework.security.acls.jdbc.JdbcMutableAclService.createAcl(JdbcMutableAclService.java:107)
    at za.org.grassroot.services.GroupAccessControlManager.addUserGroupPermissions(GroupAccessControlManager.java:61)

**Comment by luke-grassroot** [comment]
Fixed with a recent commit, but now having issues with CurrentUserController advice ... Cycling into a new issue.
