### ISSUE TITLE
After user is given a role in a group, authenticator throws error

### ISSUE THREAD

**Issue by luke-grassroot** [grassrootza/grassroot-platform#49]
After adding the role group_organizer to myself on my test group, homepage doesn't work. Pasting various logs ...

**Comment by luke-grassroot** [comment]
2015-12-13 20:14:25.320 ERROR 3809 --- [http-nio-8443-exec-3] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.ClassCastException: java.lang.String cannot be cast to org.springframework.security.core.userdetails.UserDetails] with root cause

java.lang.ClassCastException: java.lang.String cannot be cast to org.springframework.security.core.userdetails.UserDetails
	at za.org.grassroot.webapp.controller.webapp.CurrentUserControllerAdvice.getCurrentUser(CurrentUserControllerAdvice.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

**Comment by luke-grassroot** [comment]
This was after the following (also logs, masking phone number & username):

2015-12-13 20:11:31.132  INFO 3809 --- [http-nio-8443-exec-8] z.o.g.w.c.webapp.AdminController         : Found this user ... User{firstName='Luke', lastName='Jordan', phoneNumber='27xxxxxx', displayName='Luke Jordan', languageCode='en', id=1, createdDateTime=2015-10-30 19:00:26.174, username='27xxxxxxx', enabled=true, version=197}
2015-12-13 20:11:31.137  INFO 3809 --- [http-nio-8443-exec-8] z.o.g.w.c.webapp.AdminController         : Role name retrieved: ROLE_GROUP_ORGANIZER
2015-12-13 20:11:31.137  INFO 3809 --- [http-nio-8443-exec-8] z.o.g.w.c.webapp.AdminController         : About to do role assignment etc ... Role: ROLE_GROUP_ORGANIZER ... to user ... Luke Jordan ... to group ... Testing group
2015-12-13 20:11:31.147  INFO 3809 --- [http-nio-8443-exec-8] za.org.grassroot.services.RoleManager    : Created this new role: Role{role name='ROLE_GROUP_ORGANIZER', groupReferenceId ='1', groupReferenceName ='Testinggroup', id=null, type=GROUP, permissions=[]}
2015-12-13 20:11:31.203  INFO 3809 --- [http-nio-8443-exec-8] za.org.grassroot.services.RoleManager    : Role saved as ... Role{role name='ROLE_GROUP_ORGANIZER', groupReferenceId ='1', groupReferenceName ='Testinggroup', id=7, type=GROUP, permissions=[GROUP_PERMISSION_FORCE_ADD_MEMBER, GROUP_PERMISSION_AUTHORIZE_SUBGROUP, GROUP_PERMISSION_DELETE_GROUP_MEMBER, GROUP_PERMISSION_DELINK_SUBGROUP, GROUP_PERMISSION_ADD_GROUP_MEMBER, GROUP_PERMISSION_UPDATE_GROUP_DETAILS]}
2015-12-13 20:11:31.212  INFO 3809 --- [http-nio-8443-exec-8] z.o.g.s.GroupAccessControlManager        : ZOG: Adding permissions for this group ... Group{groupName='Testing group', id=1, createdDateTime=2015-10-30 19:03:10.187, createdByUser=User{firstName='Luke', lastName='Jordan', phoneNumber='27xxxxxxxx', displayName='Luke Jordan', languageCode='en', id=1, createdDateTime=2015-10-30 19:00:26.174, username='27xxxxxxxxx', enabled=true, version=197}, reminderMinutes=0, version=15, parent=null}
2015-12-13 20:11:31.213  INFO 3809 --- [http-nio-8443-exec-8] z.o.g.s.GroupAccessControlManager        : ZOG: Adding them to this user ... User{firstName='Luke', lastName='Jordan', phoneNumber='27xxxxxxxxxxxxx, displayName='Luke Jordan', languageCode='en', id=1, createdDateTime=2015-10-30 19:00:26.174, username='27xxxxxxxxxx', enabled=true, version=197}
2015-12-13 20:11:31.213  INFO 3809 --- [http-nio-8443-exec-8] z.o.g.s.GroupAccessControlManager        : ZOG: Adding this set of permissions ... [GROUP_PERMISSION_FORCE_ADD_MEMBER, GROUP_PERMISSION_AUTHORIZE_SUBGROUP, GROUP_PERMISSION_DELETE_GROUP_MEMBER, GROUP_PERMISSION_DELINK_SUBGROUP, GROUP_PERMISSION_ADD_GROUP_MEMBER, GROUP_PERMISSION_UPDATE_GROUP_DETAILS]

**Comment by luke-grassroot** [comment]
The code that calls just before that is pretty straightforward (the prior form is a bit of a hack, has multiple drop down boxes named as role_ + user Id, hence just the getparam):

String roleName = request.getParameter("role_" + userId);
roleManagementService.addDefaultRoleToGroupAndUser(roleName, group, userToModify);

**Comment by luke-grassroot** [comment]
Adding to above, to recreate:

1 -- Make yourself an admin user (manual insert into roles table)
2 -- Log into web app, will see "System Admin" button on top row, click on it
3 -- Go to "groups" from the admin home
4 -- Pick a group (obv need to create one if not created yet)
5 -- List of group members will come up, with drop down boxes for roles -- next to yourself, select "group organizer" from the box and hit "update role"
6 -- Click on "Grassroot" in top left to go home, or log out and log in, or any other way to go home

**Comment by luke-grassroot** [comment]
Update on this issue. It is confined to the browser session during which the user assigns a group role to itself or to any other user.

So, to replicate, do as above, except that in step 5, can assign a role to any user (not just to yourself). Then will get an error on any page, however going there (via link, top left button, typing URL). Close the browser, open again, and the problem disappears.

Hence, not currently a very high priority. However, leaving the issue open as will need to fix it eventually.

**Comment by lesetse** [comment]
@luke-grassroot  please re-test when you get a chance
